package species

// Registry is the single source of truth for all biological data in simuz.
// Contains apex competitors, ancient builders, isolationists, monsters, and wildlife.
var Registry = map[string]Species{

	// =========================================================================
	// 1. THE TWIN APEX COMPETITORS
	// =========================================================================
	"human": {
		ID:                  "human",
		Name:                "Human",
		MaxAge:              80,
		AdultAge:            16,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      1200,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 259200,
		MaleNames:           []string{"Aldric", "Cedric", "Eamon", "Gareth", "Ivan", "Kol", "Nolan", "Soren", "Baron", "Jussi", "Jaak", "Pekka", "Meelis", "Oskar", "Tanel"},
		FemaleNames:         []string{"Aldrica", "Brenna", "Delara", "Fiona", "Hilda", "Jenna", "Lyssa", "Maren", "Opal", "Petra", "Rhea", "Tessa", "Katriin", "Mai", "Laine"},
		BaseAttrs:           Attributes{STR: 10, DEX: 10, CON: 10, INT: 10, WIS: 10, CHA: 10},
		FluidBiology:        false,
		PreferredBiomes:     []string{"plains", "forest"},
	},
	"orc": {
		ID:                  "orc",
		Name:                "Orc",
		MaxAge:              45,
		AdultAge:            5,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:      1000,
		DefaultScripts:      []string{"aggressive", "raiding"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 172800,
		MaleNames:           []string{"Mürsk", "Kolge", "Raudrusikas", "Põmm", "Kivirind", "Porinägu", "Räme", "Kolv", "Mudaauk", "Kirvespea", "Murru", "Rusk", "Känd", "Tont", "Päts"},
		FemaleNames:         []string{"Mürina", "Raudmeel", "Kiviraev", "Rabakoll", "Poritallaja", "Raskesaabas", "Kandiline", "Tormi", "Teravnuga", "Karuema", "Kandamil", "Sõjatrumm", "Tahmasilm", "Raudnõges", "Põlendik"},
		BaseAttrs:           Attributes{STR: 14, DEX: 10, CON: 13, INT: 6, WIS: 6, CHA: 5},
		FluidBiology:        false,
		PreferredBiomes:     []string{"waste", "swamp", "highlands"},
	},

	// =========================================================================
	// 2. THE ANCIENT WORLD BUILDERS & ISOLATIONISTS
	// =========================================================================
	"elf": {
		ID:                  "elf",
		Name:                "Elf",
		MaxAge:              700,
		AdultAge:            100,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      1500,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 345600,
		MaleNames:           []string{"Leoleht", "Urmasvalg", "Sinitäht", "Kuuvarjund", "Tuulepesa", "Kuldvibu", "Hõbejuus", "Aasalaul", "Vihmatants", "Valguse", "Kastepiisk", "Smaragdi", "Tähesära", "Pilvepiir", "Ojahein"},
		FemaleNames:         []string{"Ilmatar", "Kastepärl", "Päikesekiir", "Uduloor", "Ööbiku", "Sireli", "Lilleleht", "Helendus", "Kuldjuus", "Hingelind", "Metsapiiga", "Allikavesi", "Pilvetee", "Õiesilm", "Härmatis"},
		BaseAttrs:           Attributes{STR: 9, DEX: 13, CON: 9, INT: 13, WIS: 12, CHA: 11},
		FluidBiology:        false,
		PreferredBiomes:     []string{"forest"},
	},
	"dwarf": {
		ID:                  "dwarf",
		Name:                "Dwarf",
		MaxAge:              200,
		AdultAge:            25,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      1200,
		DefaultScripts:      []string{"defensive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 259200,
		MaleNames:           []string{"Mägra", "Kullakang", "Sepapoiss", "Kirka", "Suurkivi", "Õllevaat", "Habeme", "Kaevur", "Raudsaabas", "Söetolm", "Graniit", "Tõrvik", "Kamm", "Vaskne", "Paas"},
		FemaleNames:         []string{"Malm", "Kalliskivi", "Ahjusoe", "Raudvara", "Kullasoon", "Keldri", "Pliit", "Kõvakivi", "Sepapiiga", "Alasi", "Pätsike", "Hõbevalge", "Mõõdulint", "Kirkasilm", "Väävel"},
		BaseAttrs:           Attributes{STR: 12, DEX: 8, CON: 14, INT: 11, WIS: 10, CHA: 7},
		FluidBiology:        false,
		PreferredBiomes:     []string{"highlands"},
	},
	"hobbit": {
		ID:                  "hobbit",
		Name:                "Hobbit",
		MaxAge:              100,
		AdultAge:            22,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      1100,
		DefaultScripts:      []string{"defensive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 200000,
		MaleNames:           []string{"Peeter", "Toivo", "Lembit", "Heiki", "Oskar", "Arvo", "Valdur", "Prits", "Vello"},
		FemaleNames:         []string{"Mai", "Tiiu", "Laine", "Ene", "Pille", "Reet", "Urve", "Salme", "Viivi"},
		BaseAttrs:           Attributes{STR: 7, DEX: 13, CON: 11, INT: 9, WIS: 11, CHA: 12},
		FluidBiology:        false,
		PreferredBiomes:     []string{"plains"},
	},

	// =========================================================================
	// 3. THE FLUID AND MONSTROUS SUBTERRANEAN FACTIONS
	// =========================================================================
	"fey": {
		ID:                  "fey",
		Name:                "Fey",
		MaxAge:              300,
		AdultAge:            40,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      900,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "none",
		AutoFeed:            true,
		StarvationThreshold: 86400,
		MaleNames:           []string{"Sirts", "Päkapikk", "Kihulane", "Säde", "Putukas", "Okas", "Tirtsu", "Kärbseseen", "Virvendus", "Pilveke", "Tuulispask"},
		FemaleNames:         []string{"Marjake", "Liblikas", "Mesilane", "Lepatriinu", "Kastepiiga", "Õietolm", "Nõgese", "Kullake", "Pärlake", "Haldjatants"},
		BaseAttrs:           Attributes{STR: 5, DEX: 15, CON: 8, INT: 12, WIS: 10, CHA: 14},
		FluidBiology:        true,
		PreferredBiomes:     []string{"forest", "swamp"},
	},
	"kobold": {
		ID:                  "kobold",
		Name:                "Kobold",
		MaxAge:              25,
		AdultAge:            4,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      400,
		DefaultScripts:      []string{"kobold"},
		DefaultSleepCycle:   "nocturnal",
		AutoFeed:            true,
		StarvationThreshold: 129600,
		MaleNames:           []string{"Andres", "Margus", "Toomas", "Kristjan", "Martin", "Priit", "Sander", "Indrek", "Jaan", "Markus", "Rasmus"},
		FemaleNames:         []string{"Mari", "Katriin", "Triin", "Pille", "Kadri", "Tiina", "Laura", "Eveli", "Sirje", "Kristel", "Anu"},
		BaseAttrs:           Attributes{STR: 7, DEX: 15, CON: 9, INT: 8, WIS: 8, CHA: 5},
		FluidBiology:        false,
		PreferredBiomes:     []string{"highlands", "waste"},
	},
	"minotaur": {
		ID:                  "minotaur",
		Name:                "Minotaur",
		MaxAge:              120,
		AdultAge:            15,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:      1400,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 200000,
		MaleNames:           []string{"Sõnn", "Sarvik", "Rümp", "Kandam", "Sõlg", "Mürakas", "Turjakas", "Sõraline", "Maamurdja"},
		FemaleNames:         []string{"Lehma", "Sarve", "Uhta", "Mürina", "Sõra", "Kandiline", "Raskejalg", "Mullaema", "Tormirind"},
		BaseAttrs:           Attributes{STR: 18, DEX: 8, CON: 16, INT: 5, WIS: 9, CHA: 4},
		FluidBiology:        false,
		PreferredBiomes:     []string{"waste", "highlands"},
	},
	"goblin": {
		ID:                  "goblin",
		Name:                "Goblin",
		MaxAge:              35,
		AdultAge:            8,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      600,
		DefaultScripts:      []string{"gathering"},
		DefaultSleepCycle:   "nocturnal",
		AutoFeed:            true,
		StarvationThreshold: 129600,
		MaleNames:           []string{"Göz", "Snag", "Grib", "Nog", "Blink", "Mug", "Skars", "Riz", "Gnak", "Gub"},
		FemaleNames:         []string{"Sizz", "Griz", "Noga", "Blin", "Muga", "Vexa", "Skra", "Zil", "Gna", "Greem"},
		BaseAttrs:           Attributes{STR: 8, DEX: 13, CON: 10, INT: 9, WIS: 7, CHA: 6},
		FluidBiology:        false,
		PreferredBiomes:     []string{"forest", "swamp"},
	},

	// =========================================================================
	// 4. THE ACCURSED AND SPECULATIVE MONSTERS
	// =========================================================================
	"vampire": {
		ID:                  "vampire",
		Name:                "Vampire",
		MaxAge:              9999,
		AdultAge:            20,
		CanLevelUp:          true,
		CanReproduce:        false,
		IsCaveman:           false,
		IsImmortal:          true,
		GestationTicks:      0,
		DefaultScripts:      []string{"vampire"},
		DefaultSleepCycle:   "nocturnal",
		AutoFeed:            false,
		StarvationThreshold: 86400,
		MaleNames:           []string{"Verelind", "Öölane", "Krahv", "Varjund", "Külm", "Kirstu", "Sääsk", "Nahkhiir"},
		FemaleNames:         []string{"Udupiiga", "Ööliblikas", "Verihein", "Külmavares", "Varjualune", "Kirstune", "Kiin"},
		BaseAttrs:           Attributes{STR: 15, DEX: 14, CON: 12, INT: 14, WIS: 11, CHA: 15},
		FluidBiology:        false,
		PreferredBiomes:     []string{"swamp", "forest"},
	},
	"werewolf": {ID: "werewolf", Name: "Werewolf", MaxAge: 90, AdultAge: 16, CanLevelUp: true, CanReproduce: true, IsCaveman: true, IsImmortal: false, GestationTicks: 1000, DefaultScripts: []string{"werewolf"}, DefaultSleepCycle: "nocturnal", AutoFeed: true, StarvationThreshold: 172800, MaleNames: []string{"Hundi", "Kriimsilm", "Võsavillem", "Murru", "Kutsu", "Ugu", "Hunts", "Kihv"}, FemaleNames: []string{"Ema-hunt", "Võsapiiga", "Kriima", "Murra", "Kutsika", "Uga", "Kihva", "Teravhamb"}, BaseAttrs: Attributes{STR: 16, DEX: 12, CON: 15, INT: 7, WIS: 8, CHA: 5}, FluidBiology: true, PreferredBiomes: []string{"forest", "highlands"}},
	// =========================================================================
	// // 5. WILDLIFE ECOSYSTEM TIERS
	"wolf":  {ID: "wolf", Name: "Wolf", MaxAge: 15, AdultAge: 2, CanLevelUp: false, CanReproduce: true, IsCaveman: true, IsImmortal: false, GestationTicks: 300, DefaultScripts: []string{"defensive"}, DefaultSleepCycle: "nocturnal", AutoFeed: true, StarvationThreshold: 172800, MaleNames: []string{"Hallard", "Võsa", "Villem", "Susi", "Kriim", "Kõri"}, FemaleNames: []string{"Halli", "Võsu", "Sillem", "Suse", "Kriima", "Kõra"}, BaseAttrs: Attributes{STR: 10, DEX: 12, CON: 11, INT: 3, WIS: 8, CHA: 2}, FluidBiology: false, PreferredBiomes: []string{"forest", "highlands", "plains"}},
	"sheep": {ID: "sheep", Name: "Sheep", MaxAge: 12, AdultAge: 1, CanLevelUp: false, CanReproduce: true, IsCaveman: false, IsImmortal: false, GestationTicks: 250, DefaultScripts: []string{"defensive"}, DefaultSleepCycle: "diurnal", AutoFeed: true, StarvationThreshold: 86400, MaleNames: []string{"Oinas", "Villak", "Päss", "Uru", "Murdja", "Tutt"}, FemaleNames: []string{"Struu", "Kee", "Mää", "Mute", "Villane", "Utte", "Tutta"}, BaseAttrs: Attributes{STR: 4, DEX: 6, CON: 8, INT: 1, WIS: 4, CHA: 5}, FluidBiology: false, PreferredBiomes: []string{"plains"}},
	"bear":  {ID: "bear", Name: "Bear", MaxAge: 30, AdultAge: 4, CanLevelUp: false, CanReproduce: true, IsCaveman: true, IsImmortal: false, GestationTicks: 400, DefaultScripts: []string{"defensive"}, DefaultSleepCycle: "diurnal", AutoFeed: true, StarvationThreshold: 400000, MaleNames: []string{"Karu", "Ott", "Mesikäpp", "Päts", "Mõmm", "Kõvamees", "Pruun"}, FemaleNames: []string{"Ema-karu", "Oti", "Mesikäpa", "Pätsi", "Mõmmi", "Pruuni", "Mesine"}, BaseAttrs: Attributes{STR: 16, DEX: 7, CON: 16, INT: 3, WIS: 9, CHA: 3}, FluidBiology: false, PreferredBiomes: []string{"highlands", "forest"}},
}
