package species

// Registry is the single source of truth for all biological data in simuz.
// Contains apex competitors, ancient builders, isolationists, monsters, and wildlife.
var Registry = map[string]Species{

	// =========================================================================
	// 1. THE TWIN APEX COMPETITORS
	// =========================================================================
	"human": {
		ID:                  "human",
		Name:                "Human",
		MaxAge:              80,
		AdultAge:            16,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      1200,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 259200,
		MaleNames:           []string{"Aldric", "Cedric", "Eamon", "Gareth", "Ivan", "Kol", "Nolan", "Soren", "Baron", "Jussi", "Jaak", "Pekka", "Meelis", "Oskar", "Tanel"},
		FemaleNames:         []string{"Aldrica", "Brenna", "Delara", "Fiona", "Hilda", "Jenna", "Lyssa", "Maren", "Opal", "Petra", "Rhea", "Tessa", "Katriin", "Mai", "Laine"},
		BaseAttrs:           Attributes{STR: 10, DEX: 10, CON: 10, INT: 10, WIS: 10, CHA: 10},
		FluidBiology:        false,
		PreferredBiomes:     []string{"plains", "forest"},
	},
	"orc": {
		ID:                  "orc",
		Name:                "Orc",
		MaxAge:              45,
		AdultAge:            5,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:      1000,
		DefaultScripts:      []string{"aggressive", "raiding"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 172800,
		MaleNames:           []string{"Mürsk", "Kolge", "Raudrusikas", "Põmm", "Kivirind", "Porinägu", "Räme", "Kolv", "Mudaauk", "Kirvespea", "Murru", "Rusk", "Känd", "Tont", "Päts"},
		FemaleNames:         []string{"Mürina", "Raudmeel", "Kiviraev", "Rabakoll", "Poritallaja", "Raskesaabas", "Kandiline", "Tormi", "Teravnuga", "Karuema", "Kandamil", "Sõjatrumm", "Tahmasilm", "Raudnõges", "Põlendik"},
		BaseAttrs:           Attributes{STR: 14, DEX: 10, CON: 13, INT: 6, WIS: 6, CHA: 5},
		FluidBiology:        false,
		PreferredBiomes:     []string{"waste", "swamp", "highlands"},
	},

	// =========================================================================
	// 2. THE ANCIENT WORLD BUILDERS & ISOLATIONISTS
	// =========================================================================
	"elf": {
		ID:                  "elf",
		Name:                "Elf",
		MaxAge:              700,
		AdultAge:            100,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      1500,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 345600,
		MaleNames:           []string{"Leoleht", "Urmasvalg", "Sinitäht", "Kuuvarjund", "Tuulepesa", "Kuldvibu", "Hõbejuus", "Aasalaul", "Vihmatants", "Valguse", "Kastepiisk", "Smaragdi", "Tähesära", "Pilvepiir", "Ojahein"},
		FemaleNames:         []string{"Ilmatar", "Kastepärl", "Päikesekiir", "Uduloor", "Ööbiku", "Sireli", "Lilleleht", "Helendus", "Kuldjuus", "Hingelind", "Metsapiiga", "Allikavesi", "Pilvetee", "Õiesilm", "Härmatis"},
		BaseAttrs:           Attributes{STR: 9, DEX: 13, CON: 9, INT: 13, WIS: 12, CHA: 11},
		FluidBiology:        false,
		PreferredBiomes:     []string{"forest"},
	},
	"dwarf": {
		ID:                  "dwarf",
		Name:                "Dwarf",
		MaxAge:              200,
		AdultAge:            25,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      1200,
		DefaultScripts:      []string{"defensive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 259200,
		MaleNames:           []string{"Mägra", "Kullakang", "Sepapoiss", "Kirka", "Suurkivi", "Õllevaat", "Habeme", "Kaevur", "Raudsaabas", "Söetolm", "Graniit", "Tõrvik", "Kamm", "Vaskne", "Paas"},
		FemaleNames:         []string{"Malm", "Kalliskivi", "Ahjusoe", "Raudvara", "Kullasoon", "Keldri", "Pliit", "Kõvakivi", "Sepapiiga", "Alasi", "Pätsike", "Hõbevalge", "Mõõdulint", "Kirkasilm", "Väävel"},
		BaseAttrs:           Attributes{STR: 12, DEX: 8, CON: 14, INT: 11, WIS: 10, CHA: 7},
		FluidBiology:        false,
		PreferredBiomes:     []string{"highlands"},
	},
	"hobbit": {
		ID:                  "hobbit",
		Name:                "Hobbit",
		MaxAge:              100,
		AdultAge:            22,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      1100,
		DefaultScripts:      []string{"defensive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 200000,
		MaleNames:           []string{"Peeter", "Toivo", "Lembit", "Heiki", "Oskar", "Arvo", "Valdur", "Prits", "Vello"},
		FemaleNames:         []string{"Mai", "Tiiu", "Laine", "Ene", "Pille", "Reet", "Urve", "Salme", "Viivi"},
		BaseAttrs:           Attributes{STR: 7, DEX: 13, CON: 11, INT: 9, WIS: 11, CHA: 12},
		FluidBiology:        false,
		PreferredBiomes:     []string{"plains"},
	},

	// =========================================================================
	// 3. THE FLUID AND MONSTROUS SUBTERRANEAN FACTIONS
	// =========================================================================
	"fey": {
		ID:                  "fey",
		Name:                "Fey",
		MaxAge:              300,
		AdultAge:            40,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      900,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "none",
		AutoFeed:            true,
		StarvationThreshold: 86400,
		MaleNames:           []string{"Sirts", "Päkapikk", "Kihulane", "Säde", "Putukas", "Okas", "Tirtsu", "Kärbseseen", "Virvendus", "Pilveke", "Tuulispask"},
		FemaleNames:         []string{"Marjake", "Liblikas", "Mesilane", "Lepatriinu", "Kastepiiga", "Õietolm", "Nõgese", "Kullake", "Pärlake", "Haldjatants"},
		BaseAttrs:           Attributes{STR: 5, DEX: 15, CON: 8, INT: 12, WIS: 10, CHA: 14},
		FluidBiology:        true,
		PreferredBiomes:     []string{"forest", "swamp"},
	},
	"kobold": {
		ID:                  "kobold",
		Name:                "Kobold",
		MaxAge:              25,
		AdultAge:            4,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      400,
		DefaultScripts:      []string{"kobold"},
		DefaultSleepCycle:   "nocturnal",
		AutoFeed:            true,
		StarvationThreshold: 129600,
		MaleNames:           []string{"Andres", "Margus", "Toomas", "Kristjan", "Martin", "Priit", "Sander", "Indrek", "Jaan", "Markus", "Rasmus"},
		FemaleNames:         []string{"Mari", "Katriin", "Triin", "Pille", "Kadri", "Tiina", "Laura", "Eveli", "Sirje", "Kristel", "Anu"},
		BaseAttrs:           Attributes{STR: 7, DEX: 15, CON: 9, INT: 8, WIS: 8, CHA: 5},
		FluidBiology:        false,
		PreferredBiomes:     []string{"highlands", "waste"},
	},
	"minotaur": {
		ID:                  "minotaur",
		Name:                "Minotaur",
		MaxAge:              120,
		AdultAge:            15,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:      1400,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 200000,
		MaleNames:           []string{"Sõnn", "Sarvik", "Rümp", "Kandam", "Sõlg", "Mürakas", "Turjakas", "Sõraline", "Maamurdja"},
		FemaleNames:         []string{"Lehma", "Sarve", "Uhta", "Mürina", "Sõra", "Kandiline", "Raskejalg", "Mullaema", "Tormirind"},
		BaseAttrs:           Attributes{STR: 18, DEX: 8, CON: 16, INT: 5, WIS: 9, CHA: 4},
		FluidBiology:        false,
		PreferredBiomes:     []string{"waste", "highlands"},
	},
	"goblin": {
		ID:                  "goblin",
		Name:                "Goblin",
		MaxAge:              35,
		AdultAge:            8,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      600,
		DefaultScripts:      []string{"gathering"},
		DefaultSleepCycle:   "nocturnal",
		AutoFeed:            true,
		StarvationThreshold: 129600,
		MaleNames:           []string{"Göz", "Snag", "Grib", "Nog", "Blink", "Mug", "Skars", "Riz", "Gnak", "Gub"},
		FemaleNames:         []string{"Sizz", "Griz", "Noga", "Blin", "Muga", "Vexa", "Skra", "Zil", "Gna", "Greem"},
		BaseAttrs:           Attributes{STR: 8, DEX: 13, CON: 10, INT: 9, WIS: 7, CHA: 6},
		FluidBiology:        false,
		PreferredBiomes:     []string{"forest", "swamp"},
	},

	// =========================================================================
	// 4. THE ACCURSED AND SPECULATIVE MONSTERS
	// =========================================================================
	"vampire": {
		ID:                  "vampire",
		Name:                "Vampire",
		MaxAge:              9999,
		AdultAge:            20,
		CanLevelUp:          true,
		CanReproduce:        false,
		IsCaveman:           false,
		IsImmortal:          true,
		GestationTicks:      0,
		DefaultScripts:      []string{"vampire"},
		DefaultSleepCycle:   "nocturnal",
		AutoFeed:            false,
		StarvationThreshold: 86400,
		MaleNames:           []string{"Verelind", "Öölane", "Krahv", "Varjund", "Külm", "Kirstu", "Sääsk", "Nahkhiir"},
		FemaleNames:         []string{"Udupiiga", "Ööliblikas", "Verihein", "Külmavares", "Varjualune", "Kirstune", "Kiin"},
		BaseAttrs:           Attributes{STR: 15, DEX: 14, CON: 12, INT: 14, WIS: 11, CHA: 15},
		FluidBiology:        false,
		PreferredBiomes:     []string{"swamp", "forest"},
	},
	"werewolf": {ID: "werewolf", Name: "Werewolf", MaxAge: 90, AdultAge: 16, CanLevelUp: true, CanReproduce: true, IsCaveman: true, IsImmortal: false, GestationTicks: 1000, DefaultScripts: []string{"werewolf"}, DefaultSleepCycle: "nocturnal", AutoFeed: true, StarvationThreshold: 172800, MaleNames: []string{"Hundi", "Kriimsilm", "Võsavillem", "Murru", "Kutsu", "Ugu", "Hunts", "Kihv"}, FemaleNames: []string{"Ema-hunt", "Võsapiiga", "Kriima", "Murra", "Kutsika", "Uga", "Kihva", "Teravhamb"}, BaseAttrs: Attributes{STR: 16, DEX: 12, CON: 15, INT: 7, WIS: 8, CHA: 5}, FluidBiology: true, PreferredBiomes: []string{"forest", "highlands"}},
	// =========================================================================
	// // 5. WILDLIFE ECOSYSTEM TIERS
	"wolf":  {ID: "wolf", Name: "Wolf", MaxAge: 15, AdultAge: 2, CanLevelUp: false, CanReproduce: true, IsCaveman: true, IsImmortal: false, GestationTicks: 300, DefaultScripts: []string{"defensive"}, DefaultSleepCycle: "nocturnal", AutoFeed: true, StarvationThreshold: 172800, MaleNames: []string{"Hallard", "Võsa", "Villem", "Susi", "Kriim", "Kõri"}, FemaleNames: []string{"Halli", "Võsu", "Sillem", "Suse", "Kriima", "Kõra"}, BaseAttrs: Attributes{STR: 10, DEX: 12, CON: 11, INT: 3, WIS: 8, CHA: 2}, FluidBiology: false, PreferredBiomes: []string{"forest", "highlands", "plains"}},
	"sheep": {ID: "sheep", Name: "Sheep", MaxAge: 12, AdultAge: 1, CanLevelUp: false, CanReproduce: true, IsCaveman: false, IsImmortal: false, GestationTicks: 250, DefaultScripts: []string{"defensive"}, DefaultSleepCycle: "diurnal", AutoFeed: true, StarvationThreshold: 86400, MaleNames: []string{"Oinas", "Villak", "Päss", "Uru", "Murdja", "Tutt"}, FemaleNames: []string{"Struu", "Kee", "Mää", "Mute", "Villane", "Utte", "Tutta"}, BaseAttrs: Attributes{STR: 4, DEX: 6, CON: 8, INT: 1, WIS: 4, CHA: 5}, FluidBiology: false, PreferredBiomes: []string{"plains"}},
	"bear":  {ID: "bear", Name: "Bear", MaxAge: 30, AdultAge: 4, CanLevelUp: false, CanReproduce: true, IsCaveman: true, IsImmortal: false, GestationTicks: 400, DefaultScripts: []string{"defensive"}, DefaultSleepCycle: "diurnal", AutoFeed: true, StarvationThreshold: 400000, MaleNames: []string{"Karu", "Ott", "Mesikäpp", "Päts", "Mõmm", "Kõvamees", "Pruun"}, FemaleNames: []string{"Ema-karu", "Oti", "Mesikäpa", "Pätsi", "Mõmmi", "Pruuni", "Mesine"}, BaseAttrs: Attributes{STR: 16, DEX: 7, CON: 16, INT: 3, WIS: 9, CHA: 3}, FluidBiology: false, PreferredBiomes: []string{"highlands", "forest"}},

	// =========================================================================
	// 6. BEASTIAL MONSTERS & ABERRATIONS
	// =========================================================================
	"bugbear": {
		ID:                  "bugbear",
		Name:                "Bugbear",
		MaxAge:              50,
		AdultAge:            12,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:       600,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "nocturnal",
		AutoFeed:            true,
		StarvationThreshold: 172800,
		MaleNames:           []string{"Grum", "Skraal", "Throk", "Gnash", "Murg", "Brog", "Krag", "Vorn"},
		FemaleNames:         []string{"Grakka", "Skraala", "Thrikka", "Nasha", "Murga", "Broga", "Kragga", "Vorni"},
		BaseAttrs:           Attributes{STR: 15, DEX: 13, CON: 13, INT: 8, WIS: 9, CHA: 8},
		FluidBiology:        false,
		PreferredBiomes:     []string{"forest", "highlands", "waste"},
	},
	"hobgoblin": {
		ID:                  "hobgoblin",
		Name:                "Hobgoblin",
		MaxAge:              60,
		AdultAge:            10,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:       500,
		DefaultScripts:      []string{"aggressive", "defensive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 129600,
		MaleNames:           []string{"Korag", "Mog", "Durg", "Balg", "Krosh", "Tog", "Narg", "Zug"},
		FemaleNames:         []string{"Koraga", "Moga", "Durga", "Balga", "Krosha", "Toga", "Narga", "Zuga"},
		BaseAttrs:           Attributes{STR: 13, DEX: 12, CON: 12, INT: 11, WIS: 10, CHA: 10},
		FluidBiology:        false,
		PreferredBiomes:     []string{"highlands", "plains", "waste"},
	},
	"lizardfolk": {
		ID:                  "lizardfolk",
		Name:                "Lizardfolk",
		MaxAge:              60,
		AdultAge:            14,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:       700,
		DefaultScripts:      []string{"lizardfolk"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 129600,
		MaleNames:           []string{"Sssral", "Kroth", "Viss", "Targ", "Nekk", "Scaly", "Jash", "Morr"},
		FemaleNames:         []string{"Sssrina", "Krotha", "Vissa", "Targa", "Nekka", "Scalya", "Jasha", "Morra"},
		BaseAttrs:           Attributes{STR: 14, DEX: 11, CON: 14, INT: 8, WIS: 12, CHA: 7},
		FluidBiology:        false,
		PreferredBiomes:     []string{"swamp", "forest"},
	},
	"gnoll": {
		ID:                  "gnoll",
		Name:                "Gnoll",
		MaxAge:              40,
		AdultAge:            8,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:       500,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "nocturnal",
		AutoFeed:            true,
		StarvationThreshold: 86400,
		MaleNames:           []string{"Yarg", "Grum", "Skar", "Thok", "Vorn", "Razz", "Muk", "Klik"},
		FemaleNames:         []string{"Yargra", "Gruma", "Skara", "Thoka", "Vorna", "Razza", "Muka", "Klika"},
		BaseAttrs:           Attributes{STR: 14, DEX: 11, CON: 13, INT: 7, WIS: 10, CHA: 8},
		FluidBiology:        false,
		PreferredBiomes:     []string{"plains", "waste"},
	},
	"griffin": {
		ID:                  "griffin",
		Name:                "Griffin",
		MaxAge:              40,
		AdultAge:            5,
		CanLevelUp:          false,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:       800,
		DefaultScripts:      []string{"defensive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 129600,
		MaleNames:           []string{"Aurelius", "Goldwing", "Stormclaw", "Skymane"},
		FemaleNames:         []string{"Aurelia", "Goldfeather", "Stormwing", "Skyclaw"},
		BaseAttrs:           Attributes{STR: 17, DEX: 14, CON: 15, INT: 5, WIS: 12, CHA: 8},
		FluidBiology:        false,
		PreferredBiomes:     []string{"highlands", "mountains"},
	},
	"wyvern": {
		ID:                  "wyvern",
		Name:                "Wyvern",
		MaxAge:              80,
		AdultAge:            3,
		CanLevelUp:          false,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:       500,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "nocturnal",
		AutoFeed:            true,
		StarvationThreshold: 86400,
		MaleNames:           []string{"Stingwing", "Venomclaw", "Duskscale", "Razorspike"},
		FemaleNames:         []string{"Venomwing", "Stingclaw", "Duskfeather", "Razorsting"},
		BaseAttrs:           Attributes{STR: 18, DEX: 13, CON: 16, INT: 6, WIS: 12, CHA: 8},
		FluidBiology:        false,
		PreferredBiomes:     []string{"waste", "highlands", "cave"},
	},
	"hydra": {
		ID:                  "hydra",
		Name:                "Hydra",
		MaxAge:              200,
		AdultAge:            10,
		CanLevelUp:          false,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:       1000,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "none",
		AutoFeed:            true,
		StarvationThreshold: 0,
		MaleNames:           []string{"Vornax", "Crothos", "Drakulus", "Serpentrix"},
		FemaleNames:         []string{"Vornaxia", "Crothossa", "Drakulissa", "Serpentrixa"},
		BaseAttrs:           Attributes{STR: 20, DEX: 10, CON: 20, INT: 4, WIS: 11, CHA: 5},
		FluidBiology:        false,
		PreferredBiomes:     []string{"swamp", "waste"},
	},
	"basilisk": {
		ID:                  "basilisk",
		Name:                "Basilisk",
		MaxAge:              50,
		AdultAge:            3,
		CanLevelUp:          false,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:       400,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "nocturnal",
		AutoFeed:            true,
		StarvationThreshold: 86400,
		MaleNames:           []string{"Stonegaze", "Duskbane", "Petravox", "Gorgrox"},
		FemaleNames:         []string{"Stonestare", "Duskvenom", "Petraffin", "Gorgrix"},
		BaseAttrs:           Attributes{STR: 14, DEX: 8, CON: 16, INT: 2, WIS: 10, CHA: 6},
		FluidBiology:        false,
		PreferredBiomes:     []string{"waste", "highlands"},
	},
	"cockatrice": {
		ID:                  "cockatrice",
		Name:                "Cockatrice",
		MaxAge:              20,
		AdultAge:            1,
		CanLevelUp:          false,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:       200,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "nocturnal",
		AutoFeed:            true,
		StarvationThreshold: 43200,
		MaleNames:           []string{"Pettrix", "Stoneplume", "Gazeclaw", "Serpentis"},
		FemaleNames:         []string{"Pettrixa", "Stoneplum", "Gazeclaw", "Serpentia"},
		BaseAttrs:           Attributes{STR: 6, DEX: 12, CON: 11, INT: 2, WIS: 9, CHA: 5},
		FluidBiology:        false,
		PreferredBiomes:     []string{"plains", "forest", "waste"},
	},
	"manticore": {
		ID:                  "manticore",
		Name:                "Manticore",
		MaxAge:              60,
		AdultAge:            4,
		CanLevelUp:          false,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:       500,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "nocturnal",
		AutoFeed:            true,
		StarvationThreshold: 86400,
		MaleNames:           []string{"Spikeclaw", "Venomsting", "Fangedune", "Scalefang"},
		FemaleNames:         []string{"Spikewing", "Venomsting", "Fangedune", "Scalemouth"},
		BaseAttrs:           Attributes{STR: 17, DEX: 13, CON: 15, INT: 7, WIS: 10, CHA: 8},
		FluidBiology:        false,
		PreferredBiomes:     []string{"waste", "forest", "highlands"},
	},
	"skeleton": {
		ID:                  "skeleton",
		Name:                "Skeleton",
		MaxAge:              9999,
		AdultAge:            1,
		CanLevelUp:          false,
		CanReproduce:        false,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:       0,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "none",
		AutoFeed:            false,
		StarvationThreshold: 0,
		MaleNames:           []string{"Bones", "Rattle", "Skull", "Decay", "Osteon"},
		FemaleNames:         []string{"Bonea", "Rattla", "Skulla", "Decaya", "Osteona"},
		BaseAttrs:           Attributes{STR: 11, DEX: 12, CON: 0, INT: 3, WIS: 8, CHA: 3},
		FluidBiology:        false,
		PreferredBiomes:     []string{"waste", "highlands", "cave"},
	},
	"zombie": {
		ID:                  "zombie",
		Name:                "Zombie",
		MaxAge:              9999,
		AdultAge:            1,
		CanLevelUp:          false,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:       0,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "none",
		AutoFeed:            false,
		StarvationThreshold: 0,
		MaleNames:           []string{"Rotter", "Shambler", "Ghoulkin", "Drool", "Stench"},
		FemaleNames:         []string{"Rotta", "Shambla", "Ghoulkie", "Stencha", "Fester"},
		BaseAttrs:           Attributes{STR: 13, DEX: 6, CON: 0, INT: 2, WIS: 6, CHA: 3},
		FluidBiology:        false,
		PreferredBiomes:     []string{"waste", "swamp", "forest"},
	},
	"ghoul": {
		ID:                  "ghoul",
		Name:                "Ghoul",
		MaxAge:              9999,
		AdultAge:            1,
		CanLevelUp:          false,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:       0,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "nocturnal",
		AutoFeed:            false,
		StarvationThreshold: 0,
		MaleNames:           []string{"Carnor", "Rotsnout", "Clawjaw", "Grip", "Hollow"},
		FemaleNames:         []string{"Carnora", "Rotsnouta", "Clawjaw", "Gripa", "Hollowa"},
		BaseAttrs:           Attributes{STR: 13, DEX: 14, CON: 0, INT: 9, WIS: 11, CHA: 6},
		FluidBiology:        false,
		PreferredBiomes:     []string{"waste", "highlands", "cave"},
	},
	"lich": {
		ID:                  "lich",
		Name:                "Lich",
		MaxAge:              9999,
		AdultAge:            20,
		CanLevelUp:          true,
		CanReproduce:        false,
		IsCaveman:           false,
		IsImmortal:          true,
		GestationTicks:       0,
		DefaultScripts:      []string{"aggressive", "necromancer"},
		DefaultSleepCycle:   "none",
		AutoFeed:            false,
		StarvationThreshold: 0,
		MaleNames:           []string{"Xarth", "Korvinus", "Valdris", "Malachar", "Kaelthorn", "Dreiss"},
		FemaleNames:         []string{"Xarista", "Korvinara", "Valdriss", "Malachara", "Kaelthorna", "Dreissa"},
		BaseAttrs:           Attributes{STR: 12, DEX: 11, CON: 0, INT: 22, WIS: 18, CHA: 16},
		FluidBiology:        false,
		PreferredBiomes:     []string{"waste", "highlands", "cave"},
	},
	"wraith": {
		ID:                  "wraith",
		Name:                "Wraith",
		MaxAge:              9999,
		AdultAge:            1,
		CanLevelUp:          false,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:       0,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "none",
		AutoFeed:            false,
		StarvationThreshold: 0,
		MaleNames:           []string{"Shade", "Wisp", "Fade", "Wraith", "Gloom"},
		FemaleNames:         []string{"Shadea", "Wispa", "Fadea", "Wraitha", "Glooma"},
		BaseAttrs:           Attributes{STR: 0, DEX: 16, CON: 0, INT: 12, WIS: 12, CHA: 15},
		FluidBiology:        false,
		PreferredBiomes:     []string{"waste", "forest", "cave"},
	},
	"mind_flayer": {
		ID:                  "mind_flayer",
		Name:                "Mind Flayer",
		MaxAge:              120,
		AdultAge:            20,
		CanLevelUp:          true,
		CanReproduce:        false,
		IsCaveman:           false,
		IsImmortal:          true,
		GestationTicks:       0,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "none",
		AutoFeed:            false,
		StarvationThreshold: 0,
		MaleNames:           []string{"Thal'Zir", "Xyr'Keth", "Nar'Zul", "Cerebrix", "Psi'Lath"},
		FemaleNames:         []string{"Thal'Zira", "Xyr'Ketha", "Nar'Zula", "Cerebrixa", "Psi'Latha"},
		BaseAttrs:           Attributes{STR: 11, DEX: 12, CON: 12, INT: 19, WIS: 17, CHA: 17},
		FluidBiology:        false,
		PreferredBiomes:     []string{"waste", "swamp", "underdark"},
	},
	"beholder": {
		ID:                  "beholder",
		Name:                "Beholder",
		MaxAge:              200,
		AdultAge:            10,
		CanLevelUp:          false,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:       1500,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "none",
		AutoFeed:            false,
		StarvationThreshold: 0,
		MaleNames:           []string{"Eye-of-Dread", "Orbius", "Tyrant-Sight", "All-See"},
		FemaleNames:         []string{"Eye-of-Terror", "Orbia", "Tyrant-Gaze", "All-Seea"},
		BaseAttrs:           Attributes{STR: 10, DEX: 14, CON: 18, INT: 17, WIS: 15, CHA: 17},
		FluidBiology:        false,
		PreferredBiomes:     []string{"waste", "highlands", "cave"},
	},
	"troll": {
		ID:                  "troll",
		Name:                "Troll",
		MaxAge:              100,
		AdultAge:            5,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:       800,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "none",
		AutoFeed:            true,
		StarvationThreshold: 86400,
		MaleNames:           []string{"Stump", "Rubble", "Thorn", "Grot", "Mossback"},
		FemaleNames:         []string{"Stumpa", "Rubblea", "Thorna", "Grota", "Mossbacka"},
		BaseAttrs:           Attributes{STR: 19, DEX: 11, CON: 18, INT: 6, WIS: 9, CHA: 6},
		FluidBiology:        false,
		PreferredBiomes:     []string{"forest", "swamp", "waste"},
	},
	"ogre": {
		ID:                  "ogre",
		Name:                "Ogre",
		MaxAge:              80,
		AdultAge:            15,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:       1000,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 172800,
		MaleNames:           []string{"Gorrox", "Bogrot", "Thud", "Snaga", "Murgosh"},
		FemaleNames:         []string{"Gorroxa", "Bogrota", "Thuda", "Snaga", "Murgosha"},
		BaseAttrs:           Attributes{STR: 17, DEX: 9, CON: 15, INT: 7, WIS: 8, CHA: 7},
		FluidBiology:        false,
		PreferredBiomes:     []string{"waste", "highlands", "plains"},
	},
	"ettin": {
		ID:                  "ettin",
		Name:                "Ettin",
		MaxAge:              120,
		AdultAge:            12,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:       1200,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 200000,
		MaleNames:           []string{"Doublebrain", "Twinsmash", "Duug", "Bash", "Grone"},
		FemaleNames:         []string{"Doublebraina", "Twinsmasher", "Duuga", "Basha", "Gronea"},
		BaseAttrs:           Attributes{STR: 20, DEX: 7, CON: 17, INT: 6, WIS: 10, CHA: 7},
		FluidBiology:        false,
		PreferredBiomes:     []string{"highlands", "waste", "cave"},
	},
	"cyclops": {
		ID:                  "cyclops",
		Name:                "Cyclops",
		MaxAge:              200,
		AdultAge:            20,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           true,
		IsImmortal:          false,
		GestationTicks:       1500,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 200000,
		MaleNames:           []string{"Barga", "Skotthelm", "Roke", "Uluk", "Thraka"},
		FemaleNames:         []string{"Bargai", "Skothelm", "Roka", "Uluki", "Thraka"},
		BaseAttrs:           Attributes{STR: 22, DEX: 10, CON: 18, INT: 9, WIS: 12, CHA: 9},
		FluidBiology:        false,
		PreferredBiomes:     []string{"mountains", "waste", "highlands"},
	},
	"medusa": {
		ID:                  "medusa",
		Name:                "Medusa",
		MaxAge:              300,
		AdultAge:            25,
		CanLevelUp:          true,
		CanReproduce:        false,
		IsCaveman:           false,
		IsImmortal:          true,
		GestationTicks:       0,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            false,
		StarvationThreshold: 0,
		MaleNames:           []string{"Serpentis", "Gorgax"},
		FemaleNames:         []string{"Medusy", "Gorgara", "Serpentis", "Basilissa"},
		BaseAttrs:           Attributes{STR: 18, DEX: 10, CON: 14, INT: 14, WIS: 16, CHA: 14},
		FluidBiology:        false,
		PreferredBiomes:     []string{"cave", "waste", "highlands"},
	},
	"floating_eye": {
		ID:                  "floating_eye",
		Name:                "Floating Eye",
		MaxAge:              9999,
		AdultAge:            1,
		CanLevelUp:          false,
		CanReproduce:        false,
		IsCaveman:           true,
		IsImmortal:          true,
		GestationTicks:       0,
		DefaultScripts:      []string{"scouting"},
		DefaultSleepCycle:   "none",
		AutoFeed:            false,
		StarvationThreshold: 0,
		MaleNames:           []string{"Orbix", "Gleam", "Watcher", "Peer"},
		FemaleNames:         []string{"Orbia", "Gleama", "Watchara", "Peera"},
		BaseAttrs:           Attributes{STR: 0, DEX: 10, CON: 0, INT: 14, WIS: 16, CHA: 12},
		FluidBiology:        false,
		PreferredBiomes:     []string{"swamp", "cave", "underdark"},
	},
	"half_orc": {
		ID:                  "half_orc",
		Name:                "Half-Orc",
		MaxAge:              75,
		AdultAge:            16,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      1100,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 259200,
		MaleNames:           []string{"Grolf", "Krom", "Thok", "Brak", "Drog", "Mog", "Urgal", "Garok"},
		FemaleNames:         []string{"Krelka", "Draga", "Shaka", "Greta", "Lara", "Orsha", "Bruna", "Hurga"},
		BaseAttrs:           Attributes{STR: 14, DEX: 10, CON: 14, INT: 7, WIS: 8, CHA: 7},
		FluidBiology:        false,
		PreferredBiomes:     []string{"plains", "highlands", "waste"},
	},
	"half_elf": {
		ID:                  "half_elf",
		Name:                "Half-Elf",
		MaxAge:              120,
		AdultAge:            16,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      1100,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 259200,
		MaleNames:           []string{"Aldric", "Cedric", "Eamon", "Gareth", "Thalor", "Elric", "Caelum", "Fenrik"},
		FemaleNames:         []string{"Aldrica", "Brenna", "Delara", "Fiona", "Thalyra", "Elyra", "Caelia", "Riven"},
		BaseAttrs:           Attributes{STR: 10, DEX: 11, CON: 10, INT: 11, WIS: 11, CHA: 11},
		FluidBiology:        false,
		PreferredBiomes:     []string{"forest", "plains"},
	},
	"half_dwarf": {
		ID:                  "half_dwarf",
		Name:                "Half-Dwarf",
		MaxAge:              90,
		AdultAge:            16,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      1100,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 259200,
		MaleNames:           []string{"Dorn", "Brik", "Haldor", "Grund", "Torin", "Baldur", "Fjor", "Erik"},
		FemaleNames:         []string{"Dessa", "Brynn", "Hilda", "Greta", "Torva", "Barda", "Fjora", "Astrid"},
		BaseAttrs:           Attributes{STR: 12, DEX: 8, CON: 14, INT: 8, WIS: 9, CHA: 8},
		FluidBiology:        false,
		PreferredBiomes:     []string{"highlands", "mountains", "plains"},
	},
	"half_goblin": {
		ID:                  "half_goblin",
		Name:                "Half-Goblin",
		MaxAge:              55,
		AdultAge:            16,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      1000,
		DefaultScripts:      []string{"gathering"},
		DefaultSleepCycle:   "nocturnal",
		AutoFeed:            true,
		StarvationThreshold: 172800,
		MaleNames:           []string{"Snag", "Grib", "Nog", "Blink", "Mog", "Rik", "Wix", "Zep"},
		FemaleNames:         []string{"Grix", "Nix", "Plix", "Wyna", "Bria", "Mika", "Trix", "Flick"},
		BaseAttrs:           Attributes{STR: 8, DEX: 13, CON: 9, INT: 5, WIS: 7, CHA: 7},
		FluidBiology:        false,
		PreferredBiomes:     []string{"waste", "plains", "forest"},
	},
	"half_hobgoblin": {
		ID:                  "half_hobgoblin",
		Name:                "Half-Hobgoblin",
		MaxAge:              65,
		AdultAge:            16,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      1050,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "diurnal",
		AutoFeed:            true,
		StarvationThreshold: 172800,
		MaleNames:           []string{"Durgath", "Skarrak", "Mograth", "Karg", "Brak", "Zol", "Vorn", "Ghrak"},
		FemaleNames:         []string{"Krel", "Shara", "Nixa", "Greta", "Velka", "Dasha", "Kira", "Zara"},
		BaseAttrs:           Attributes{STR: 12, DEX: 10, CON: 12, INT: 7, WIS: 8, CHA: 7},
		FluidBiology:        false,
		PreferredBiomes:     []string{"highlands", "plains", "waste"},
	},
	"half_gnoll": {
		ID:                  "half_gnoll",
		Name:                "Half-Gnoll",
		MaxAge:              60,
		AdultAge:            16,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      1050,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "nocturnal",
		AutoFeed:            true,
		StarvationThreshold: 172800,
		MaleNames:           []string{"Ripper", "Bonepick", "Snapper", "Gorr", "Ashclaw", "Maw", "Vex", "Grak"},
		FemaleNames:         []string{"Ripsnout", "Mama", "Vexa", "Grix", "Bonea", "Snapa", "Graw", "Krela"},
		BaseAttrs:           Attributes{STR: 12, DEX: 11, CON: 11, INT: 4, WIS: 7, CHA: 5},
		FluidBiology:        false,
		PreferredBiomes:     []string{"plains", "waste"},
	},
	"half_kobold": {
		ID:                  "half_kobold",
		Name:                "Half-Kobold",
		MaxAge:              50,
		AdultAge:            16,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      1000,
		DefaultScripts:      []string{"kobold"},
		DefaultSleepCycle:   "nocturnal",
		AutoFeed:            true,
		StarvationThreshold: 172800,
		MaleNames:           []string{"Skrit", "Yip", "Klik", "Drak", "Snik", "Rix", "Zik", "Vrik"},
		FemaleNames:         []string{"Skrix", "Yipa", "Klika", "Draka", "Snika", "Rika", "Zika", "Vrika"},
		BaseAttrs:           Attributes{STR: 7, DEX: 14, CON: 8, INT: 6, WIS: 7, CHA: 6},
		FluidBiology:        false,
		PreferredBiomes:     []string{"underground", "cave", "waste"},
	},
	"half_fey": {
		ID:                  "half_fey",
		Name:                "Half-Fey",
		MaxAge:              100,
		AdultAge:            16,
		CanLevelUp:          true,
		CanReproduce:        true,
		IsCaveman:           false,
		IsImmortal:          false,
		GestationTicks:      1100,
		DefaultScripts:      []string{"aggressive"},
		DefaultSleepCycle:   "nocturnal",
		AutoFeed:            true,
		StarvationThreshold: 259200,
		MaleNames:           []string{"Thorn", "Bram", "Alder", "Rowan", "Briar", "Fenn", "Oaken", "Willow"},
		FemaleNames:         []string{"Thyra", "Briar", "Alda", "Rowan", "Nyx", "Luma", "Sylph", "Faye"},
		BaseAttrs:           Attributes{STR: 8, DEX: 12, CON: 9, INT: 10, WIS: 12, CHA: 13},
		FluidBiology:        false,
		PreferredBiomes:     []string{"forest", "swamp", "plains"},
	},
}

// HalfSpeciesMap defines which species pairs can crossbreed and what half-species they produce.
// Both directions are supported (A+B and B+A).
var HalfSpeciesMap = map[string]map[string]string{
	"human":  {"orc": "half_orc", "elf": "half_elf", "dwarf": "half_dwarf", "goblin": "half_goblin", "hobgoblin": "half_hobgoblin", "gnoll": "half_gnoll", "kobold": "half_kobold", "fey": "half_fey"},
	"orc":    {"human": "half_orc"},
	"elf":    {"human": "half_elf"},
	"dwarf":  {"human": "half_dwarf"},
	"goblin": {"human": "half_goblin"},
	"hobgoblin": {"human": "half_hobgoblin"},
	"gnoll":  {"human": "half_gnoll"},
	"kobold": {"human": "half_kobold"},
	"fey":    {"human": "half_fey"},
}

// GetHalfSpecies returns the half-species ID if speciesA and speciesB can crossbreed,
// or an empty string if the combination is not valid.
func GetHalfSpecies(speciesA, speciesB string) string {
	if pairs, ok := HalfSpeciesMap[speciesA]; ok {
		if child, ok := pairs[speciesB]; ok {
			return child
		}
	}
	return ""
}

// CanCrossbreed returns true if both species can reproduce and are compatible for crossbreeding.
func CanCrossbreed(speciesA, speciesB string) bool {
	if speciesA == speciesB {
		a, ok := GetByID(speciesA)
		return ok && a.CanReproduce
	}
	return GetHalfSpecies(speciesA, speciesB) != ""
}

